@startuml parisportif

class User{
    - id
    - login
    - email
    - gender
    - lastName
    - firstName
    - phoneNumber
    - birthDate
    - avatar
    - linkToOfficialId
    - Adress
    - wallet

    + createUser()
    + editUser()
    + deleteUser()
    + proofUpper18()
    + bet()
    + addMoney()
    + withdrawMoney()
    + addFavorite()
    + removeFavorite()
}

class Adress{
    - id
    - userId
    - streetNb
    - street
    - zipCode
    - city
    - country
}


class Wallet{
    - userId
    - balance

    + getHistoryOfMovement()
    + addMoney()
    + removeMoney()
}

class Basket{
    - userId
    - amount
    - listOfBet

    + addBetToBasket()
    + removeBetToBasket()
    + editBetToBasket()
    + validate()
}



class Bet{
    - name
    - orderFinishTime
    - odds
    - result
    - eventId
    - participantId
    - team_or_playersolo


    + createBet()
    + editBet()
    + deleteBet()
    + getResultofBet()
    + setBonusToParticipantId()
}


class Event{
    - name
    - categorie
    - location
    - dateEvent
    - dateTimeZone
    - nbContestant
}

class Event_Participant{
    - eventId
    - participantId
    - team_or_playersolo
    - bonus_malus
}

class Team{
    - name
    - categorie
    - nbPlayer
    - ranking

    + calculateRanking()
}

class Player{
    - lastName
    - firstName
    - status
    - ranking(premier temps donné, puis calculé par la suite)
}

class PlayerRanking{
    - playerId
    - age
    - healthRate
    - offensiveRate
    - defensiveRate
}

class Team_Player{
    - teamId
    - playerId
}

class Competition{
    - name
    - StartDate
    - FinishDate
    - nbTeam
}

@enduml
