name: CI

on: 
  push:
    branches:
  pull_request:
    branches:

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
      
    steps:

      - name: Copy Symfony CI environment
        run: |
          cd code
          ls
          cp .env.test .env

      - name: Verify MySQL connection from container 
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          sudo mysql --host mysql -uroot -ppassword -e "SHOW DATABASES"  

      - uses: actions/checkout@v1
      - name: Run Composer
        run: |
          cd code
          composer install --prefer-dist

      - name: Run phpunit
        run: |
          cd code
          ./vendor/bin/simple-phpunit
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}

      - name: Run phpcbf
        run: |
          cd code
          ./vendor/bin/phpcbf
      - name: Run phpcs
        run: |
          cd code
          ./vendor/bin/phpcs



        
