name: CI

on: 
  push:
    branches:
  pull_request:
    branches:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./code

    steps:
      - uses: actions/checkout@v1
      - uses: php-actions/composer@v1
        working-directory: ${{env.working-directory}}
      - name: Run phpunit
        working-directory: ./code
        run: ./vendor/bin/simple-phpunit
      - name: Run phpcbf
        working-directory: ./code
        run: ./vendor/bin/phpcbf
      - name: Run phpcs
        working-directory: ./code
        run: ./vendor/bin/phpcs

        
