name: CI

on: 
  push:
    branches:
  pull_request:
    branches:

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mydb:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db_test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
        
    steps:
      - name: Verify MySQL connection from container 
        run: |
          apt-get update
          apt-get install -y mysql-client
          mysql --host mydb -uroot -ppassword -e "SHOW DATABASES"  

      - uses: actions/checkout@v1
      - name: Run Composer
        run: |
          cd code
          composer install --prefer-dist
      - name: Run phpunit
        env:
          DB_CONNECTION: mydb
          DB_DATABASE: db_test
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: password
        run: |
          cd code
          ./vendor/bin/simple-phpunit

      - name: Run phpcbf
        run: |
          cd code
          ./vendor/bin/phpcbf
      - name: Run phpcs
        run: |
          cd code
          ./vendor/bin/phpcs

        
