name: CI

on: 
  push:
    branches:
  pull_request:
    branches:

jobs:
  build-test:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v1
      - name: Run Composer
        run: |
          cd code
          composer install --prefer-dist
      - name: Run phpunit
        run: |
          cd code
          ./vendor/bin/simple-phpunit
      - name: Run phpcbf
        run: |
          cd code
          ./vendor/bin/phpcbf
      - name: Run phpcs
        run: |
          cd code
          ./vendor/bin/phpcs

        
