name: CI

on: 
  push:
    branches:
  pull_request:
    branches:

defaults:
  run:
    working-directory: code

jobs:
  build-test:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v1
      - name: Run Composer
        run: php-actions/composer@v2
      - name: Run phpunit
        run: ./vendor/bin/simple-phpunit
      - name: Run phpcbf
        run: ./vendor/bin/phpcbf
      - name: Run phpcs
        run: ./vendor/bin/phpcs

        
